// Indicates an exception was unexpectedly caught in the middle of a task.
exception UnexpectedException;
